# Generated by Django 3.2 on 2021-04-18 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False, verbose_name='BookID')),
                ('book_name', models.TextField(max_length=50, verbose_name='Book Name')),
                ('book_author', models.TextField(max_length=50, verbose_name='Book author')),
                ('book_avg_rating', models.IntegerField(verbose_name='Book rating')),
                ('book_isbn', models.CharField(max_length=30, verbose_name='Book ISBN')),
                ('book_language', models.CharField(max_length=10, verbose_name='Book Language')),
                ('book_pages', models.IntegerField(verbose_name='Book Pages')),
                ('book_numrating', models.IntegerField(verbose_name='Number of Rating')),
                ('book_numtext', models.IntegerField(verbose_name='Number of Text')),
                ('book_pubdate', models.DateField(verbose_name='Book publish data')),
                ('book_publisher', models.CharField(max_length=30, verbose_name='Book publisher')),
                ('book_img', models.CharField(max_length=20, verbose_name='Book Image')),
                ('book_type', models.TextField(max_length=20, verbose_name='Book type')),
            ],
            options={
                'verbose_name': 'Book Info',
                'verbose_name_plural': 'Book Info',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Lable id')),
                ('label_name', models.CharField(max_length=10, verbose_name='Lable Text')),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Label',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('order_text', models.CharField(max_length=500, verbose_name='content')),
                ('order_auther', models.CharField(max_length=20, verbose_name='user')),
                ('order_qua', models.CharField(max_length=50, verbose_name='quantity')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('rec_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('rec_auther', models.CharField(max_length=20, verbose_name='User')),
                ('rec_type', models.CharField(max_length=20, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Recommend',
                'verbose_name_plural': 'Recommend',
            },
        ),
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('dynamic_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Stat ID')),
                ('dynamic_plays', models.IntegerField(verbose_name='number of views')),
                ('dynamic_search', models.IntegerField(verbose_name='number of searchs')),
                ('dynamic_down', models.IntegerField(verbose_name='order time')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.book', verbose_name='book title')),
            ],
            options={
                'verbose_name': 'Stat',
                'verbose_name_plural': 'Stat',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='CommentID')),
                ('comment_text', models.CharField(max_length=500, verbose_name='Comment Text')),
                ('comment_user', models.CharField(max_length=20, verbose_name='Comment User')),
                ('comment_date', models.CharField(max_length=50, verbose_name='date')),
                ('comment_rate', models.IntegerField(null=True, verbose_name='Rating')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.book', verbose_name='Book title')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comment',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.label', verbose_name='book type id'),
        ),
    ]
