# Generated by Django 2.1.8 on 2021-04-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='score',
            field=models.IntegerField(default=100, verbose_name='Score'),
        ),
    ]
